Adds option to change components path
github/view_component pull request #961
Opened 2021-06-13 03:58 UTC by lfalcao

Related: #863 :clinking_glasses:

2021-06-14 08:26 UTC, Spone commented on docs/guide/generators.md
> +ViewComponent uses `app/components` as folder for components, but you can change it by adding `config.view_component.view_component_path` into your applicaton config.
The markdown linter is complaining about a missing empty line.

```suggestion
ViewComponent uses `app/components` as folder for components, but you can change it by adding `config.view_component.view_component_path` into your applicaton config.

```

2021-06-14 08:31 UTC, Spone commented on lib/rails/generators/component/component_generator.rb
> +        Rails.application.config.view_component.view_component_path || 'app/components'
```suggestion
        Rails.application.config.view_component.view_component_path || "app/components"
```

2021-06-14 08:31 UTC, Spone commented on lib/rails/generators/erb/component_generator.rb
> +        Rails.application.config.view_component.view_component_path || 'app/components'
```suggestion
        Rails.application.config.view_component.view_component_path || "app/components"
```

2021-06-14 08:31 UTC, Spone commented on lib/rails/generators/haml/component_generator.rb
> +        Rails.application.config.view_component.view_component_path || 'app/components'
```suggestion
        Rails.application.config.view_component.view_component_path || "app/components"
```

2021-06-14 08:31 UTC, Spone commented on lib/rails/generators/slim/component_generator.rb
> +        Rails.application.config.view_component.view_component_path || 'app/components'
```suggestion
        Rails.application.config.view_component.view_component_path || "app/components"
```

2021-06-14 08:31 UTC, Spone commented on test/generators/component_generator_test.rb
> +end
```suggestion
end

```

2021-06-14 08:32 UTC, Spone commented on test/test_helper.rb
> +end
```suggestion
end

```

2021-06-14 08:38 UTC, Spone commented
Looking good, thanks for contributing!

I'm wondering if we should try to make it DRY by moving the `component_path` method declaration to a `Utils` module (and including it in generator classes).

2021-06-15 01:24 UTC, lfalcao commented
@Spone Done, I thought in do that but in another time... :blush:

2021-06-15 22:15 UTC, joelhawksley approved these changes

2021-06-15 22:15 UTC, joelhawksley commented on docs/guide/generators.md
> +ViewComponent uses `app/components` as folder for components, but you can change it by adding `config.view_component.view_component_path` into your applicaton config.
```suggestion
Generated ViewComponents are added to `app/components` by default. Set `config.view_component.view_component_path` to use a different path.
```

2021-06-15 22:19 UTC, joelhawksley commented
@Spone this looks good to me. Feel free to merge when you think it's ready.

2021-06-15 23:38 UTC, Spone approved these changes

2021-06-15 23:39 UTC, Spone requested changes
@lfalcao I just noticed this PR is missing a changelog entry, can you add one please?

2021-06-21 20:07 UTC, Spone commented
Thanks @lfalcao, can you please rebase and solve the changelog conflict? Then I'll go ahead and merge!

2021-06-21 20:13 UTC, lfalcao commented
@Spone ouch, just a moment.

2021-06-21 20:43 UTC, lfalcao commented
@Spone :bow:

2021-06-21 20:52 UTC, Spone approved these changes

2021-06-21 20:53 UTC, merged